---
  - name: Import nginx.conf file
    template:
       src: nginx.conf.j2
       dest: "{{ nginx_config_dir }}/nginx.conf"
       owner: root
       group: root
       mode: 0644
    notify:
      - restart nginx
    tags:
      - nginx
      - nginx-config
