---
  - include_vars: "{{ ansible_os_family | lower }}.yml"
    tags:
     - nginx
     - nginx-install
     - nginx-config

  - name: Include OS tasks
  - include_tasks: "repo-{{ ansible_os_family | lower }}.yml"

  - import_tasks: "install.yml"

  - import_tasks: "config.yml"
