---
  - name: Add APT repository key for Debian
    apt_key:
      url: "{{ nginx_apt_repository_key_url }}"
      state: present
    when: ansible_os_family == "Debian"
    tags:
      - nginx
      - nginx-repo

  - name: Add APT repository address for Stable version Nginx for Debian
    apt_repository:
      repo: "deb {{ nginx_repository_address }}/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release }} nginx"
      state: present
      filename: 'nginx-repo'
    when: ansible_os_family == "Debian" and nginx_version == 'stable'
    register: nginx_stable
    tags:
      - nginx
      - nginx-repo

  - name: Add APT repository address for Mainline version Nginx for Debian
    apt_repository:
      repo: "deb {{ nginx_repository_address }}/mainline/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release }} nginx"
      state: present
      filename: 'nginx-repo'
    when: ansible_os_family == "Debian" and nginx_version == 'mainline'
    register: nginx_mainline
    tags:
      - nginx
      - nginx-repo

  - name: Update packages list for Debian
    apt:
      update_cache: yes
    when: nginx_stable.changed or nginx_mainline.changed and ansible_os_family == "Debian"
    tags:
      - nginx
      - nginx-repo
